<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>Chaos</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Foundation\Foundation.csproj" />
    </ItemGroup>

</Project>
