<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <NuGetAudit>false</NuGetAudit>
    </PropertyGroup>

    <PropertyGroup>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
        <UseCurrentRuntimeIdentifier Condition="'$(UseCurrentRuntimeIdentifier)' == ''">true</UseCurrentRuntimeIdentifier>
        <SelfContained Condition="'$(SelfContained)' == ''">false</SelfContained>
    </PropertyGroup>

    <PropertyGroup Condition="'$(PlatformTarget)' == 'x86'">
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x86</RuntimeIdentifier>
        <SelfContained Condition="'$(SelfContained)' == ''">false</SelfContained>
    </PropertyGroup>

    <PropertyGroup Condition="'$(PlatformTarget)' == 'x64'">
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
        <SelfContained Condition="'$(SelfContained)' == ''">false</SelfContained>
    </PropertyGroup>

    <PropertyGroup Condition="'$(PlatformTarget)' == 'arm64'">
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-arm64</RuntimeIdentifier>
        <SelfContained Condition="'$(SelfContained)' == ''">false</SelfContained>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CefSharp.Wpf.NETCore" Version="145.0.260"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
        <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.269">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
